#!/bin/bash

# requires: make, g++, autoconf, libtool, libreadline-dev, svn(subversion),git,unzip,tar,cmake, libsnappy-dev


# protobuf
cd ext
wget  https://github.com/protocolbuffers/protobuf/releases/download/v3.7.1/protobuf-cpp-3.7.1.tar.gz
tar -xzvf protobuf-cpp-3.7.1.tar.gz
mv protobuf-3.7.1/ protobuf
cd protobuf
./autogen.sh
./configure --prefix=$PWD
make -j
make check
sudo make install
sudo ldconfig

