#!/bin/bash

# requires: make, g++, autoconf, libtool, libreadline-dev, svn(subversion),git,unzip,tar,cmake, libsnappy-dev
#gaoxuan--
#因为不知道什么时候就进不去github，所以我改了下脚本，能直接下压缩包的我就先下下来了，减去了访问github这个过程

cd ext


# gtest
tar -zxf release-1.6.0.tar.gz 
rm release-1.6.0.tar.gz 
mv googletest-release-1.6.0/ gtest
cd gtest
mkdir mybuild    
cd mybuild
cmake $PWD/..
make -j
cd ..
cd ..

# glog

tar -xzf v0.3.4.tar.gz
mv glog-0.3.4/ glog
rm -fr v0.3.4.tar.gz
cd glog
./configure --prefix=$PWD
make -j
make install
cd ..

# leveldb

tar -zxf v1.9.tar.gz
mv leveldb-1.9/ leveldb
rm -fr v1.9.tar.gz
cd leveldb
make -j
make libmemenv.a
cd ..

# zeromq

tar xzf zeromq-3.2.2.tar.gz
rm zeromq-3.2.2.tar.gz
mv zeromq-3.2.2 zeromq
cd zeromq
./autogen.sh
./configure --prefix=$PWD
make -j
make install
cd ..

#gperftools
git clone git@github.com:gperftools/gperftools.git
cd gperftools
./autogen.sh
./configure --prefix=$PWD --enable-frame-pointers
make -j
make install
cd ..

#gflags

tar -xzf v2.0.tar.gz
rm v2.0.tar.gz
mv gflags-2.0/ gflags
cd gflags
./configure --prefix=$PWD
make -j
make install
cd ..

# protobuf
tar -xzvf protobuf-cpp-3.7.1.tar.gz
mv protobuf-3.7.1/ protobuf
rm -rf protobuf-cpp-3.7.1.tar.gz
cd protobuf
./autogen.sh
./configure
make
make check
sudo make install
sudo ldconfig
cd ..

